#! /usr/bin/perl 
#By Devon McBride
#############################################################
#This Perl script is called <<students>>.
#It searches the group file in /etc/ based on CRN numbers you enter
#as arguements.  You may enter as many CRN numbers as you like, but 
#you must enter at least one or you will get an error message.
#last modified 6/20/03
#############################################################

<@ARGV> or die("No CRN #s were entered. Usage: students CRN1 CRN2 ...");

open (INFILE, "<group") || die("Cannot find CRN data file");

while($line = <INFILE>)
{
    $i = 0;
    while ( $i <= $#ARGV )
    {
	if ( $line =~ /^.$ARGV[$i]/ ) 
	{		
	  @record = split(":", $line);		#splits a line with ":".
	  @students = split(",", $record[3]);	#splits students up with ",".		
	
	  ##sort(@students);	#error: Useless use of sort in void context at students.pl line 17.		
	
	  open (OUTFILE, ">$ARGV[$i]");		#opens new file to hold these ids, 
						#named with the classes CRN number.		
	  foreach $id (@students)		#prints into that new file.
	  { 
	    print OUTFILE "$id \n";
	  }
	
	  close(OUTFILE);
	}
	$i++;
    }
}
close(INFILE);

##foreach $crn (<ARGV>)			#I also attempted here to sort my files, but it didn't work.
##{
##	open(FHREAD, "$crn");
##	@a = (FHREAD);
##	close(FHREAD);		 
##	sort(@a);			
##	open(FHWRITE, ">$crn");		#<---line 40 print on closed filehandle main::FHWRITE
##	print FHWRITE @a;		#            at students.pl line 40, <> chunk 35.
##	close(FHWRITE);
##}

__END__