#!/usr/bin/perl

unshift(@INC, "/pub/cis/amoghtan/cis167p");
require "Colors.pl";

   CLS();

sub optionlist
{
	CLS();
	print " \n";
	locate(22,5);

   	print "         rmadmin\n";

	locate(3,5);

	print "           menu\n";

	locate(4,5);
	print "----------------------------\n";
	locate(5,5);
	print " 1) List Files\n";
	locate(6,5);
	print " 2) Restore Files\n";
	locate(7,5);
	print " 3) Empty Trash Can\n";
	locate(8,5);
	print " 4) Delete Files Completely\n";
	locate(9,5);
	print " 5) Quit\n";
	while(<>){last;}
}
optionlist();