#!/usr/bin/perl

sub randy
{



   $mega = int(rand(27)+1);	#Here's y'r Mega

   $#nums = 5;			#Trying to 'initialize'
   $#temp = 48;
   @temp = (0,0);
   @nums = (0,0);



   for( $i=0, $i<=47, $i++ )
   {
      $temp[$i]=0;		#Fills @temp with zeros
   }
   
   $i=0;
   while( $i <= 4 )		#Fills @n.
   {
      $x = int( rand(47) +1 );
   
      if( $temp[$x] == 0 )
      {
         $temp[$x] = 1;
         $nums[$i] = $x;
         $i++;
      }
   }
   @n = sort( {$a <=> $b} @nums );
   print "$n[0], $n[1], $n[2], $n[3], $n[4], $mega \n";
}
randy;


__END__
#/students/dmcbri01/perldirectory> perl randy
Use of uninitialized value in numeric eq (==) at randy line 23.
38, 23, 16, 43, 26, 6 
/students/dmcbri01/perldirectory> 
